[workspace]

[package]
name = "orcjit_example"
version = "0.1.0"
authors = ["Andrew R Martin <0andrewmartin0@gmail.com>"]
edition = "2018"

[dependencies]
llvm-sys = "80.1.0"
libc = "0.2"
libloading = "0.5"
