[package]
name = "cauldron"
version = "0.1.0"
authors = ["Andrew R Martin <0andrewmartin0@gmail.com>"]

[dependencies]
rusttype = "0.5.2"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["bundled"]