[package]
name = "cauldron"
version = "0.1.0"
authors = ["Andrew R Martin <0andrewmartin0@gmail.com>"]

[dependencies]
byteorder = "1.2.2"
unicode-normalization = "0.1.5"
unicode-segmentation = "1.1.0"
ropey = "0.6.3"

[dependencies.rusttype]
version = "0.5.2"
default-features = false
features = ["gpu_cache"]

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["bundled"]